on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - name: Generate .env file
        run: echo "EXPO_PUBLIC_REPORTING_API_URL=\"${{ vars.EXPO_PUBLIC_REPORTING_API_URL }}\"\nEXPO_PUBLIC_UPDATE_API_URL=\"${{ vars.EXPO_PUBLIC_UPDATE_API_URL }}\"" > ./.env
      - run: npm ci
      - run: npx expo prebuild --clean --platform android
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false
      - run: ./gradlew --no-daemon packageRelease
        working-directory: "android"
      - run: mv ./android/app/build/outputs/apk/release/app-release.apk ./zs2-aplikacja.apk
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            ./zs2-aplikacja.apk
            ./app.json
